### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 16
lora_dropout: 0.05
lora_target: all

### dataset
dataset: seeclick
template: qwen2_vl
cutoff_len: 768
overwrite_cache: true
preprocessing_num_workers: 60
dataloader_num_workers: 4

### output
output_dir: saves/seeclick-qwen-vl/lora/sft
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
weight_decay: 0.1
adam_beta2: 0.95
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
gradient_checkpointing: true

### deepspeed
deepspeed: examples/deepspeed/ds_z2_config.json

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500